# Generated by Django 4.0.5 on 2022-06-20 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_course_name_course_course_firstname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course_firstname',
            new_name='course_name',
        ),
    ]
