# Generated by Django 4.0.5 on 2022-06-17 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=30)),
                ('course_fees', models.DecimalField(decimal_places=3, max_digits=10)),
                ('course_credit', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Facult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facult_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=30)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=3)),
                ('image', models.ImageField(upload_to=None)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.course')),
            ],
        ),
        migrations.CreateModel(
            name='Depart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depart_name', models.CharField(max_length=30)),
                ('facult_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.facult')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='depart_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.depart'),
        ),
    ]
